server:
  port: 9000

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/guess_the_number
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

